version: "3.3"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - .:/home/odoo/app
      - volume01:/var/lib/odoo

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  volume01: {}